### ISSUE TITLE
Verify NullDB and Couchbase api/server GetServices is working

### ISSUE THREAD

**Issue by vgunning** [sigma-dev/sigma#312] opened 2017-08-11 15:27 UTC
Verify that the NullDB and Couchbase tests for GetServices actually works

##### Description

A TODO was written wondering if the nulldb and couchbase GetServices was functioning.

##### Sigma Configuration

Run tests with both couchbase and nulldb

**Comment by meganokeefe** [comment] 2017-08-16 12:16
Is this a duplicate of #316 now?

**Comment by mcaulfield** [comment] 2017-10-11 16:09
Stale.

**Closed by mcaulfield** 2017-10-11 16:09 UTC
Labels: bug
